CREATE DATABASE DB_DATABASE;

CREATE USER DB_USER WITH REPLICATION ENCRYPTED PASSWORD 'DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE DB_DATABASE TO DB_USER;

CREATE USER DB_REPL_USER WITH REPLICATION ENCRYPTED PASSWORD 'DB_REPL_PASSWORD';

\connect DB_DATABASE;

CREATE TABLE IF NOT EXISTS phone_numbers (
    id SERIAL PRIMARY KEY,
    phone_number VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS email(
    id SERIAL PRIMARY KEY,
    email VARCHAR(255)
);

INSERT INTO email (email) VALUES ('test1@email.ru'), ('test2@example.com');
INSERT INTO phone_numbers (phone_number) VALUES ('8 (987) 653-21-23'), ('8 (900) 202-00-12');